export const REGISTRATION_COMPLETED = 'REGISTRATION_COMPLETED'
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED'
export const LOGIN_FAILED = 'LOGIN_FAILED'
